
typedef enum
{
	MENU_CONTEXT_MAIN = 0,
	
		MENU_CONTEXT_ALIGNMENT = 1000,
			MENU_CONTEXT_ONE_STAR_ALIGN = 1100,
			MENU_CONTEXT_TWO_STAR_ALIGN = 1200,
			MENU_CONTEXT_THREE_STAR_ALIGN = 1300,
				MENU_CONTEXT_ALIGNMENT_STAR_CONTROL = 12001,
			MENU_CONTEXT_TARGET_SYNC = 1400,
			MENU_CONTEXT_POLE_AXIS_DEV = 1500,
			MENU_CONTEXT_RA_BKBLASH_CORR = 1600,
			MENU_CONTEXT_DEC_BKLASH_CORR = 1700,
		MENU_CONTEXT_NAVIGATION = 2000,
			MENU_CONTEXT_NAVIGATION_SOLAR_SYSTEM = 2100,
			MENU_CONTEXT_NAVIGATION_CONSTELLATION = 2200,
			MENU_CONTEXT_NAVIGATION_FAMOUS_STAR = 2300,
			MENU_CONTEXT_NAVIGATION_MESSIER_CAT = 2400,
			MENU_CONTEXT_NAVIGATION_NGC_CAT = 2500,
			MENU_CONTEXT_NAVIGATION_IC_CAT = 2600,
			MENU_CONTEXT_NAVIGATION_SH2_CAT = 2700,
			MENU_CONTEXT_NAVIGATION_BRIGHT_STAR = 2800,
			MENU_CONTEXT_NAVIGATION_SAO_CAT = 2900,
			MENU_CONTEXT_NAVIGATION_CUST_OBJ = 2110,
			MENU_CONTEXT_NAVIGATION_RA_DEC = 2120,
			MENU_CONTEXT_NAVIGATION_CUST_LAND = 2130,
		MENU_CONTEXT_UTILITIES = 3000,
		MENU_CONTEXT_SETUP = 4000,
			MENU_CONTEXT_AZ_EQU = 4500,
				MENU_CONTEXT_MOUNT_AZ = 46001,
				MENU_CONTEXT_MOUNT_EQU = 46002,
			MENU_CONTEXT_RESET = 4900,
				MENU_CONTEXT_RESET_CONFIRM = 100,
	
} MENU_CONTEX_ID;

typedef enum
{
	MENU_ROTATING_SPEED_1 = 1,
	MENU_ROTATING_SPEED_2 = 2,
	MENU_ROTATING_SPEED_8 = 3,
	MENU_ROTATING_SPEED_16 = 4,
	MENU_ROTATING_SPEED_64 = 5,
	MENU_ROTATING_SPEED_128 = 6,
	MENU_ROTATING_SPEED_256 = 7,
	MENU_ROTATING_SPEED_512 = 8,
	MENU_ROTATING_SPEED_MAX = 9,
	
} MENU_ROTATING_SPEED;

