
#include <LPC214x.h>

#define GPIO_LED2 (1 << 16) //P0.16
#define GPIO_LED2_OFF (IO0CLR = GPIO_LED2)
#define GPIO_LED2_ON (IO0SET = GPIO_LED2)

#define GPIO_LED1_3 (1 << 13) //P0.13
#define GPIO_LED1_3_OFF (IO0SET = GPIO_LED1_3)
#define GPIO_LED1_3_ON (IO0CLR = GPIO_LED1_3)

#define GPIO_FLASH_CS (1 << 24) //P1.24
#define ENABLE_FLASH_CS (IO1CLR = GPIO_FLASH_CS)
#define DISABLE_FLASH_CS (IO1SET = GPIO_FLASH_CS)

#define GPIO_FONTROM_CS (1 << 25) //P1.25
#define ENABLE_FONTROM_CS (IO1CLR = GPIO_FONTROM_CS)
#define DISABLE_FONTROM_CS (IO1SET = GPIO_FONTROM_CS)

#define GPIO_LCD_CS (1 << 10) //P0.10
#define ENABLE_LCD_CS (IOCLR0 |= GPIO_LCD_CS)
#define DISABLE_LCD_CS (IOSET0 |= GPIO_LCD_CS)

#define GPIO_LCD_SCLK (1 << 12) //P0.12
#define LCD_SCLK_LO (IO0CLR |= GPIO_LCD_SCLK)
#define LCD_SCLK_HI (IO0SET |= GPIO_LCD_SCLK)

#define GPIO_LCD_SID (1 << 15) //P0.15
#define LCD_SID_LO (IO0CLR |= GPIO_LCD_SID)
#define LCD_SID_HI (IO0SET |= GPIO_LCD_SID)

#define GPIO_LCD_RS (1 << 23) //P1.23
#define LCD_RS_CONTROL (IO1CLR |= GPIO_LCD_RS)
#define LCD_RS_DATA (IO1SET |= GPIO_LCD_RS)

#define GPIO_BUZZER (1 << 22) //P1.22
#define BUZZER_HI (IO1SET = GPIO_BUZZER)
#define BUZZER_LO (IO1CLR = GPIO_BUZZER)

