################################################################################
################################################################################
##
## Makefile.config -- project specific makefile to run build on sub directories
##
################################################################################
################################################################################
ifndef TERM
  HOST ?= win32
  ROOT ?=
else
  ifeq ("$(TERM)","cygwin")
    HOST ?= cygwin32
    ROOT ?= /cygdrive
  else
    HOST ?= linux
    ROOT ?=
  endif
endif

-include $(TOPDIR)/Config.mak.$(USERNAME)
include $(TOPDIR)/Config.mak

