################################################################################
################################################################################
##
## Makefile -- makefile for env
##
## Mandatory settings:
##
## o TOPDIR      = the toplevel directory (using slashes as path separator)
## o TARGET      = the machine qualifier to generate code for
##
################################################################################
################################################################################

  TOPDIR = ..
  SUBDIR = env

include $(TOPDIR)/env/make/Makefile.config

################################################################################
# define user targets
################################################################################

default: 

clean: 

build: 

install: 

headers:

all: 

################################################################################
# include internal definitions and rules
################################################################################

include $(TOPDIR)/env/make/Makefile.rules

